<BackButton@BaseFlatIconButton>
    canvas.before:
        Color:
            rgba:
                root.theme_cls.primary_color \
                if not root.text_color else root.text_color

    size_hint_x: None
    width: dp(150)
    markup: False

    BoxLayout:
        spacing: dp(10)

        MDIcon:
            id: lbl_ic
            icon: root.icon
            theme_text_color: 'Custom'
            text_color:
                root.theme_cls.primary_color \
                if not root.text_color else root.text_color
            size_hint_x: None
            width: self.texture_size[0]

        MDLabel:
            id: lbl_txt
            text: root.text
            font_size: sp(root.font_size)
            font_name: root.font_name if root.font_name is not None else self.font_name
            can_capitalize: root.can_capitalize
            shorten: True
            theme_text_color: 'Custom'
            text_color:
                root.theme_cls.primary_color \
                if not root.text_color else root.text_color
            markup: root.markup


<HomeScreen>:
	name: 'home_screen'
	BoxLayout:
		orientation: "vertical"

		MDToolbar:
			orientation: "vertical"
			padding: 45
			spacing: 40
			size_hint_y: .25
			Label:
				font_size: 40
				text: root.title
			Label:
				font_size: 30
				text: root.subtitle


		BoxLayout:
			FloatLayout:
				orientation: 'vertical'
				MDRaisedButton:
					pos_hint: {'center_x': .5, 'center_y': .5}
					size_hint: .3, .2
					font_size: 30
					text: "Gráfico de líneas"
					on_press: 
						root.manager.transition.direction = 'left' 
						root.manager.current = 'lineplot_screen'
				MDRaisedButton:
					pos_hint: {'center_x': .5, 'center_y': .8}
					size_hint: .3, .2
					font_size: 30
					text: "Gráfico de barras"
					on_press:
						root.manager.transition.direction = 'left'  
						root.manager.current = 'displot_screen'

<LineplotScreen>:
	name: 'lineplot_screen'
	BoxLayout:
		orientation: "vertical"

		MDToolbar:
			orientation: "vertical"
			padding: 45
			spacing: 40
			size_hint_y: .25
			Label:
				font_size: 40
				text: root.title
			Label:
				font_size: 30
				text: root.subtitle

		BoxLayout:
			FloatLayout:
				orientation: 'vertical'

				BoxLayout:
					orientation: "horizontal"
					pos_hint: {"center_x": .5, "y": .9}
					BackButton:
						icon: 'arrow-left-circle'
						text: "Volver al inicio"
						on_press:
							root.manager.transition.direction = 'right' 
							root.manager.current = 'home_screen'

				MDLabel:
					pos_hint: {"x":.25, "center_y": .85}
					font_size: 30
					text: 'Realiza un gráfico de líneas.'

				MDTextField:
					id: filename
					hint_text: "Nombre del archivo"
					font_size: 30
					helper_text: "Ej: prueba.csv"
					helper_text_mode: "on_focus"
					size_hint_x: .4
					pos_hint: {"center_x":.5, "center_y": .7}
				MDRaisedButton:
					pos_hint: {'center_x': .5, 'center_y': .5}
					size_hint: .5, .1
					font_size: 30
					text: "Generar gráfico"
					on_press: root.get_filename(filename.text)

<DisplotScreen>:
	name: 'displot_screen'
	BoxLayout:
		orientation: "vertical"

		MDToolbar:
			orientation: "vertical"
			padding: 45
			spacing: 40
			size_hint_y: .25
			Label:
				font_size: 40
				text: root.title
			Label:
				font_size: 30
				text: root.subtitle

		BoxLayout:
			FloatLayout:
				orientation: 'vertical'
				BoxLayout:
					orientation: "horizontal"
					pos_hint: {"center_x": .5, "y": .9}
					BackButton:
						icon: 'arrow-left-circle'
						text: "Volver al inicio"
						on_press: 
							root.manager.transition.direction = 'right' 
							root.manager.current = 'home_screen'

				MDLabel:
					pos_hint: {"x":.25, "center_y": .85}
					font_size: 30
					text: 'Realiza un gráfico de barras.'

				MDTextField:
					id: filename
					hint_text: "Nombre del archivo"
					font_size: 30
					helper_text: "Ej: prueba.csv"
					helper_text_mode: "on_focus"
					size_hint_x: .4
					pos_hint: {"center_x":.5, "center_y": .7}
				MDTextField:
					id: column_to_plot
					hint_text: "Nombre de la columna a gráficar:"
					font_size: 30
					helper_text: "Ej: edad"
					helper_text_mode: "on_focus"
					size_hint_x: .4
					pos_hint: {"center_x":.5, "center_y": .58}
				MDTextField:
					id: xlabel
					hint_text: "Etiqueta del Eje X:"
					font_size: 30
					helper_text: "Ej: Edades"
					helper_text_mode: "on_focus"
					size_hint_x: .4
					pos_hint: {"center_x":.5, "center_y": .45}
				MDTextField:
					id: ylabel
					hint_text: "Etiqueta del Eje Y:"
					font_size: 30
					helper_text: "Ej: Número de casos"
					helper_text_mode: "on_focus"
					size_hint_x: .4
					pos_hint: {"center_x":.5, "center_y": .33}
				MDTextField:
					id: plot_title
					hint_text: "Título del gráfico:"
					font_size: 30
					helper_text: "Ej: Evolución de los casos de COVID-19"
					helper_text_mode: "on_focus"
					size_hint_x: .4
					pos_hint: {"center_x":.5, "center_y": .22}
				MDRaisedButton:
					pos_hint: {'center_x': .5, 'center_y': .1}
					size_hint: .5, .1
					font_size: 30
					text: "Generar gráfico"
					on_press: root.get_plot(filename.text,column_to_plot.text,xlabel.text,ylabel.text,plot_title.text)

ScreenManager:
	HomeScreen
	LineplotScreen
	DisplotScreen