#:import txt assets.texts

<BackButton@BaseFlatIconButton>
    canvas.before:
        Color:
            rgba:
                root.theme_cls.primary_color \
                if not root.text_color else root.text_color

    size_hint_x: None
    width: dp(150)
    markup: False

    BoxLayout:
        spacing: dp(10)

        MDIcon:
            id: lbl_ic
            icon: root.icon
            theme_text_color: 'Custom'
            text_color:
                root.theme_cls.primary_color \
                if not root.text_color else root.text_color
            size_hint_x: None
            width: self.texture_size[0]

        MDLabel:
            id: lbl_txt
            text: root.text
            font_size: sp(root.font_size)
            font_name: root.font_name if root.font_name is not None else self.font_name
            can_capitalize: root.can_capitalize
            shorten: True
            theme_text_color: 'Custom'
            text_color:
                root.theme_cls.primary_color \
                if not root.text_color else root.text_color
            markup: root.markup

<HomeScreen>:
	name: 'home_screen'
	BoxLayout:
		orientation: "vertical"

		MDToolbar:
			orientation: "vertical"
			padding: 45
			spacing: 40
			size_hint_y: .25
			Label:
				font_size: 40
				text: txt.APP_TITLE
			Label:
				font_size: 30
				text: txt.APP_SUBTITLE


		BoxLayout:
			FloatLayout:
				orientation: 'vertical'
				MDRaisedButton:
					pos_hint: {'center_x': .5, 'center_y': .5}
					size_hint: .3, .2
					font_size: 30
					text: txt.LINEPLOT_SCREEN_BUTTON_TEXT
					on_press: 
						root.manager.transition.direction = 'left' 
						root.manager.current = 'lineplot_screen'
				MDRaisedButton:
					pos_hint: {'center_x': .5, 'center_y': .8}
					size_hint: .3, .2
					font_size: 30
					text: txt.DISPLOT_SCREEN_BUTTON_TEXT
					on_press:
						root.manager.transition.direction = 'left'  
						root.manager.current = 'displot_screen'

<LineplotScreen>:
	name: 'lineplot_screen'
	BoxLayout:
		orientation: "vertical"

		MDToolbar:
			orientation: "vertical"
			padding: 45
			spacing: 40
			size_hint_y: .25
			Label:
				font_size: 40
				text: txt.APP_TITLE
			Label:
				font_size: 30
				text: txt.APP_SUBTITLE
				
		BoxLayout:
			FloatLayout:
				orientation: 'vertical'

				BoxLayout:
					orientation: "horizontal"
					pos_hint: {"center_x": .5, "y": .9}
					BackButton:
						icon: 'arrow-left-circle'
						text: txt.BACK_TO_HOME_BUTTON_TEXT
						on_press:
							root.manager.transition.direction = 'right' 
							root.manager.current = 'home_screen'

				MDLabel:
					pos_hint: {"x":.3, "center_y": .92}
					font_size: 30
					text: txt.LINEPLOT_TEXT_1

				MDTextField:
					id: filename
					hint_text: txt.FILENAME_TEXTINPUT_TEXT
					font_size: 30
					helper_text: txt.FILENAME_TEXTINPUT_HELPER_TEXT
					helper_text_mode: "on_focus"
					size_hint_x: .4
					pos_hint: {"center_x":.5, "center_y": .8}
				MDTextField:
					id: x_axis
					hint_text: txt.X_AXIS_TEXT
					font_size: 30
					helper_text: ''
					helper_text_mode: "on_focus"
					size_hint_x: .4
					pos_hint: {"center_x":.5, "center_y": .68}
				MDTextField:
					id: y_axis
					hint_text: txt.X_AXIS_TEXT
					font_size: 30
					helper_text_mode: "on_focus"
					helper_text: ''
					size_hint_x: .4
					pos_hint: {"center_x":.5, "center_y": .56}
				MDTextField:
					id: xlabel
					hint_text: txt.X_LABEL_TEXT
					font_size: 30
					helper_text_mode: "on_focus"
					helper_text: ''
					size_hint_x: .4
					pos_hint: {"center_x":.5, "center_y": .45}
				MDTextField:
					id: ylabel
					hint_text: txt.Y_LABEL_TEXT
					font_size: 30
					helper_text_mode: "on_focus"
					helper_text: ''
					size_hint_x: .4
					pos_hint: {"center_x":.5, "center_y": .35}
				MDTextField:
					id: plot_title
					hint_text: txt.PLOT_TITLE_TEXT
					font_size: 30
					helper_text: txt.PLOT_TITLE_HELPER_TEXT
					helper_text_mode: "on_focus"
					size_hint_x: .4
					pos_hint: {"center_x":.5, "center_y": .22}
				MDRaisedButton:
					pos_hint: {'center_x': .5, 'center_y': .08}
					size_hint: .5, .1
					font_size: 30
					text: txt.SHOW_PLOT_BUTTON_TEXT
					on_press: root.get_plot(filename.text,x_axis.text,y_axis.text,xlabel.text,ylabel.text,plot_title.text)

<DisplotScreen>:
	name: 'displot_screen'
	BoxLayout:
		orientation: "vertical"

		MDToolbar:
			orientation: "vertical"
			padding: 45
			spacing: 40
			size_hint_y: .25
			Label:
				font_size: 40
				text: txt.APP_TITLE
			Label:
				font_size: 30
				text: txt.APP_SUBTITLE

		BoxLayout:
			FloatLayout:
				orientation: 'vertical'
				BoxLayout:
					orientation: "horizontal"
					pos_hint: {"center_x": .5, "y": .9}
					BackButton:
						icon: 'arrow-left-circle'
						text: txt.BACK_TO_HOME_BUTTON_TEXT
						on_press: 
							root.manager.transition.direction = 'right' 
							root.manager.current = 'home_screen'

				MDLabel:
					pos_hint: {"x":.25, "center_y": .85}
					font_size: 30
					text: txt.DISPLOT_TEXT_1

				MDTextField:
					id: filename
					hint_text: txt.FILENAME_TEXTINPUT_TEXT
					font_size: 30
					helper_text: txt.FILENAME_TEXTINPUT_HELPER_TEXT
					helper_text_mode: "on_focus"
					size_hint_x: .4
					pos_hint: {"center_x":.5, "center_y": .7}
				MDTextField:
					id: column_to_plot
					hint_text: txt.COLUMN_TO_PLOT_TEXT
					font_size: 30
					helper_text: txt.COLUMN_TO_PLOT_HELPER_TEXT
					helper_text_mode: "on_focus"
					size_hint_x: .4
					pos_hint: {"center_x":.5, "center_y": .58}
				MDTextField:
					id: xlabel
					hint_text: txt.X_LABEL_TEXT
					font_size: 30
					helper_text: txt.X_LABEL_HELPER_TEXT
					helper_text_mode: "on_focus"
					size_hint_x: .4
					pos_hint: {"center_x":.5, "center_y": .45}
				MDTextField:
					id: ylabel
					hint_text: txt.Y_LABEL_TEXT
					font_size: 30
					helper_text: txt.Y_LABEL_HELPER_TEXT
					helper_text_mode: "on_focus"
					size_hint_x: .4
					pos_hint: {"center_x":.5, "center_y": .33}
				MDTextField:
					id: plot_title
					hint_text: txt.PLOT_TITLE_TEXT
					font_size: 30
					helper_text: txt.PLOT_TITLE_HELPER_TEXT
					helper_text_mode: "on_focus"
					size_hint_x: .4
					pos_hint: {"center_x":.5, "center_y": .22}
				MDRaisedButton:
					pos_hint: {'center_x': .5, 'center_y': .1}
					size_hint: .5, .1
					font_size: 30
					text: txt.SHOW_PLOT_BUTTON_TEXT
					on_press: root.get_plot(filename.text,column_to_plot.text,xlabel.text,ylabel.text,plot_title.text)

ScreenManager:
	HomeScreen
	LineplotScreen
	DisplotScreen